---
spring:
  application:
    name: spring-cloud-eureka
  profiles: xjy1
server:
 port: 8097
##表示是否将自己注册到Eureka Server，默认为true。
#eureka:
#  client:
#    register-with-eureka: false
##表示是否从Eureka Server获取注册信息，默认为true
#eureka:
#  client:
#    fetch-registry: false
eureka:
  instance:
    hostname: xjy1
#设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
#默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
  client:
    serviceUrl:
      defaultZone: http://xjy2:8098/eureka/,http://xjy3:8099/eureka/
  server:
    enable-self-preservation: false  #关闭自身检查
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: xjy2
server:
 port: 8098
eureka:
  instance:
    hostname: xjy2
  client:
    serviceUrl:
      defaultZone: http://xjy1:8097/eureka/,http://xjy3:8099/eureka/

---
spring:
  application:
    name: spring-cloud-eureka
  profiles: xjy3
server:
 port: 8099
eureka:
  instance:
    hostname: xjy3
  client:
    serviceUrl:
      defaultZone: http://xjy2:8098/eureka/,http://xjy1:8097/eureka/
