spring:
  application:
    name: spring-cloud-eureka-producer
server:
  port: 8079
eureka:
  client:
    serviceUrl:
      defaultZone: http://xjy1:8097/eureka/ #,http://xjy2:8098/eureka/,http://xjy3:8099/eureka/