spring:
  application:
    name: zuul-cluster
server:
  port: 8096
#这里的配置表示，访问/hi/** 直接重定向到spring-cloud-eureka-producer
zuul:
  routes:
    hi:
      path: /hi/**
      serviceId: spring-cloud-eureka-producer
eureka:
  client:
    serviceUrl:
      defaultZone: http://xjy1:8097/eureka/