server:
  port: 8040
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        native:
          search-locations: D:/shared #classpath:/shared # 本地文件路径
  profiles:
    active: native